### ISSUE TITLE
I used the same parameter settings and data, but I can't get the same result.

### ISSUE THREAD

**Issue by Xie-Bo-2018** [HormozdiariLab/TAD-fusion-score#3]
Hi,
I use the 5KB matrix of GM12878. The parameters of fitting are set as follows, but the model is not available. The result is as follows. Which step I am doing may be wrong?

<img width="1246" alt="屏幕快照 2019-10-16 下午3 21 46" src="https://user-images.githubusercontent.com/54306618/66897026-b5be0c80-f028-11e9-802b-129eb4c7cb5e.png">

<img width="513" alt="屏幕快照 2019-10-16 下午3 22 53" src="https://user-images.githubusercontent.com/54306618/66897100-dc7c4300-f028-11e9-8bd1-b055cef7d54b.png">

**Comment by Xie-Bo-2018** [comment]
But after I change the parameters, I can get the available models, as shown below.

<img width="1261" alt="屏幕快照 2019-10-16 下午3 40 55" src="https://user-images.githubusercontent.com/54306618/66898277-7b09a380-f02b-11e9-8dac-6a35f113e47c.png">

<img width="498" alt="屏幕快照 2019-10-16 下午3 42 21" src="https://user-images.githubusercontent.com/54306618/66898310-8eb50a00-f02b-11e9-8671-f731cb8463ba.png">

**Comment by huynhvietlinh** [comment]
I still can run the tool with your parameter setting (the first one) on our cluster, so I guess the problem may come from the CPLEX setting.
Could you try the first parameter setting again but with mx = 10 (not 100) to reduce the LP problem size?

**Comment by Xie-Bo-2018** [comment]
I changed the mx parameter to 10, but I still can't get the available model, and it seems more useful to adjust the sg and mso parameters relative to reducing the mx value, or should I install a specific version of CPLEX?

<img width="1242" alt="屏幕快照 2019-10-18 上午9 20 02" src="https://user-images.githubusercontent.com/54306618/67058689-845c5280-f188-11e9-8474-022f7598c097.png">


<img width="1258" alt="屏幕快照 2019-10-18 上午9 21 32" src="https://user-images.githubusercontent.com/54306618/67058745-b968a500-f188-11e9-9269-3c2ee0ea9ed3.png">

**Comment by huynhvietlinh** [comment]
It seems that CPLEX solver on your computer can only handle small LP problems. 
For (sg, mso, mx) = (30, 5, 100), obj function has only 465 terms. 
But for (sg, mso, mx) = (600, 50, 100), the obj function has 55050 terms. 

Can you try again with mx = 1,2,3, .. to see what is the max problem size that your CPLEX solver can handle?
How much memory CPLEX can use on your computer?

**Comment by Xie-Bo-2018** [comment]
When I just set the mx value to 1, the fit_hic_model script won't build the available model. For the memory problem that CPLEX can use on the server, when I use 1KB matrix of GM12878 data to build a model for chr1, the fit_hic_model script calls more than 500G of memory, but in the end I still can't get the available model. Do I need to select a specific version of CPLEX or specifically set the upper limit of the memory that CPLEX can use? (I am very sorry that I don't know much about CPLEX. Thank you for your patience.)

<img width="1238" alt="屏幕快照 2019-10-18 下午2 59 15" src="https://user-images.githubusercontent.com/54306618/67073334-74a93200-f1b9-11e9-9e17-0e1d1184cf73.png">

**Comment by huynhvietlinh** [comment]
Can you try with different parameters (sg, mso, mx) = (40, 5, 100), (60, 5, 100), (100, 5, 30), (150, 5, 10), ... to see if the error is caused by the LP problem size?

**Comment by Xie-Bo-2018** [comment]
(sg, mso, mx) = (40, 5, 100)
<img width="1199" alt="屏幕快照 2019-10-19 上午9 29 35" src="https://user-images.githubusercontent.com/54306618/67136015-0b75fd00-f253-11e9-81a2-c169338961fe.png">

(sg, mso, mx) = (60, 5, 100)
<img width="1239" alt="屏幕快照 2019-10-19 上午9 32 35" src="https://user-images.githubusercontent.com/54306618/67136034-6ad40d00-f253-11e9-8490-6a9c1db88ef8.png">

(sg, mso, mx) = (100, 5, 30)
<img width="1255" alt="屏幕快照 2019-10-19 上午9 53 11" src="https://user-images.githubusercontent.com/54306618/67136251-53e2ea00-f256-11e9-9963-e5428c62e137.png">

(sg, mso, mx) = (150, 5, 10)
<img width="1239" alt="屏幕快照 2019-10-19 上午9 55 04" src="https://user-images.githubusercontent.com/54306618/67136274-9278a480-f256-11e9-9691-07f8e069c0be.png">

(sg, mso, mx) = (35, 5, 30)
<img width="1242" alt="屏幕快照 2019-10-19 上午9 56 07" src="https://user-images.githubusercontent.com/54306618/67136290-c8b62400-f256-11e9-81e6-a270fdafac56.png">

(sg, mso, mx) = (30, 5, 30)
<img width="1246" alt="屏幕快照 2019-10-19 上午10 04 35" src="https://user-images.githubusercontent.com/54306618/67136372-ec2d9e80-f257-11e9-963f-76dbf205ef6c.png">

**Comment by huynhvietlinh** [comment]
Ok, so (30, 5, 30) works but (35, 5, 30) does not work.
To ensure that the problem size really does matter, could you please try with even small problems as (30, 5, 20), (40, 5, 10), (60, 5, 5).
I hope it works for these cases then we only need to check the setting of CPLEX.

**Comment by Xie-Bo-2018** [comment]
(sg, mso, mx) = (30, 5, 20)
<img width="1240" alt="屏幕快照 2019-10-19 上午10 54 06" src="https://user-images.githubusercontent.com/54306618/67136830-d53e7a80-f25e-11e9-8f9a-48bd9b6a3512.png">

(sg, mso, mx) = (40, 5, 10)
<img width="1246" alt="屏幕快照 2019-10-19 上午10 56 00" src="https://user-images.githubusercontent.com/54306618/67136838-12a30800-f25f-11e9-80a3-a26939e58ed4.png">

(sg, mso, mx) =  (60, 5, 5)
<img width="1248" alt="屏幕快照 2019-10-19 上午10 57 04" src="https://user-images.githubusercontent.com/54306618/67136847-3ebe8900-f25f-11e9-8953-5375ac3bbc1e.png">

**Comment by huynhvietlinh** [comment]
Which CPLEX license are you using? I guess you are using the free edition that limits to 1000 variables and 1000 constraints only. You can apply for a free license here
https://developer.ibm.com/docloud/blog/2019/07/04/cplex-optimization-studio-for-students-and-academics/

**Comment by Xie-Bo-2018** [comment]
The CPLEX software I downloaded earlier is a limited-problem size free version. But when I download an academic full free version, The "academic initiative" register page shows "The services are down, please try again later". Maybe I have to try again in a few days.

**Comment by Xie-Bo-2018** [comment]
I have successfully downloaded the academic version of CPLEX software and the problem has been solved. Thank you for your help.
